export let costItemStubs = [
  {
    id: 1,
    code: 'CI0010101010101',
    name: 'คอนกรีต 240 ksc (ตราCPAC)',
    dtype: 'costItem',
    type: 'MATERIAL',
    unit: 'ลบ.ม.',
    price: '1750.00',
    description: `description 1`,
    remark: 'remark 1',
  },
  {
    id: 2,
    code: 'CI0010101020101',
    name: 'เหล็กเส้นข้ออ้อย DB12 SD40 ยาว 10.00 ม.(ตราบลส.)',
    type: 'MATERIAL',
    unit: 'เส้น',
    price: '120.50',
    description: `อธิบายรายละเอียดเพิ่มเติม`,
    remark: null,
  },
  {
    id: 3,
    code: 'CI0010101030101',
    name: 'ไม้ยาง 1 1/2"x3" ยาว 3.00 ม.',
    type: 'MATERIAL',
    unit: 'ท่อน',
    price: '75.00',
    description: `อธิบายรายละเอียดเพิ่มเติม`,
    remark: null,
  },
  {
    id: 4,
    code: 'CI0010101040101',
    name: 'ปูนเอนกประสงค์ ขนาด 50 กก. (ตราเสือ)',
    type: 'MATERIAL',
    unit: 'ถุง',
    price: '125.00',
    description: `อธิบายรายละเอียดเพิ่มเติม`,
    remark: null,
  },
  {
    id: 5,
    code: 'CI0010101010101',
    name: 'ค่าแรงเทคอนกรีต',
    type: 'LABOR',
    unit: 'ลบ.ม.',
    price: '250.00',
    description: `อธิบายรายละเอียดเพิ่มเติม`,
    remark: null,
  },
  {
    id: 6,
    code: 'CI0020101010101',
    name: 'ค่าแรงก่อผนังอิฐมอญ',
    type: 'LABOR',
    unit: 'ตร.ม.',
    price: '80.00',
    description: `สำหรับงานน้อยและยาก`,
    remark: null,
  },
  {
    id: 7,
    code: 'CI0030101010101',
    name: 'ค่าเหมางานไฟฟ้า งวดที่ 1',
    type: 'HIRE',
    unit: 'งวด',
    price: '0',
    description: `ใช้สำหรับสร้างงวดงาน กรุณากรอกราคา/หน่วย`,
    remark: null,
  },
  {
    id: 8,
    code: 'CI0040101010101',
    name: 'ค่าเหมางานประปา งวดที่ 3',
    type: 'HIRE',
    unit: 'งวด',
    price: '0',
    description: `ใช้สำหรับสร้างงวดงาน กรุณากรอกราคา/หน่วย`,
    remark: null,
  },
  {
    id: 9,
    code: 'CI0020101010101',
    name: 'เครน ขนาด 25 ตัน 4 ล้อโต',
    type: 'RENTAL',
    unit: 'วัน',
    price: '2500.00',
    description: `อธิบายรายละเอียดเพิ่มเติม`,
    remark: null,
  },
  {
    id: 10,
    code: 'CI0010101010101',
    name: 'ไม้แบบ ขนาด 0.40x3.00 ม.',
    type: 'RENTAL',
    unit: 'แผ่น',
    price: '15.00',
    description: `ราคาค่าเช่า/วัน`,
    remark: null,
  },
  {
    id: 11,
    code: 'CI0010101010101',
    name: 'ค่าตู้แดง',
    type: 'ETC',
    unit: 'เดือน',
    price: '2500.00',
    description: `อธิบายรายละเอียดเพิ่มเติม`,
    remark: null,
  },
  {
    id: 12,
    code: 'CI0020101010101',
    name: 'ค่าน้ำดื่ม',
    type: 'ETC',
    unit: 'ขวด',
    price: '10.00',
    description: `อธิบายรายละเอียดเพิ่มเติม`,
    remark: null,
  },
];
