import  {
  addressStubs,
  bankAccountStubs,
  citizenStubs,
  corporateStubs,
  contactStubs,
} from '@consol/custom/custom-data.stub';

export let personStubs = [
  {
    id: 1,
    code: 'P001',
    name: `${citizenStubs[0].initname}${citizenStubs[0].firstname} ${citizenStubs[0].lastname}`,
    dtype: 'individual',
    personData: citizenStubs[0],
    address: addressStubs[0],
    contact: contactStubs[0],
    bankAccounts: [bankAccountStubs[0]],
  },
  {
    id: 2,
    code: 'P002',
    name: `${citizenStubs[1].initname}${citizenStubs[1].firstname} ${citizenStubs[1].lastname}`,
    dtype: 'individual',
    personData: citizenStubs[1],
    address: addressStubs[10],
    contact: contactStubs[1],
    bankAccounts: [bankAccountStubs[1]],
  },
  {
    id: 3,
    code: 'P003',
    name: `${citizenStubs[2].initname}${citizenStubs[2].firstname} ${citizenStubs[2].lastname}`,
    dtype: 'individual',
    personData: citizenStubs[2],
    address: addressStubs[2],
    contact: contactStubs[2],
    bankAccounts: [bankAccountStubs[2]],
  },
  {
    id: 4,
    code: 'P004',
    name: `${citizenStubs[3].initname}${citizenStubs[3].firstname} ${citizenStubs[3].lastname}`,
    dtype: 'individual',
    personData: citizenStubs[3],
    address: addressStubs[3],
    contact: contactStubs[3],
    bankAccounts: [bankAccountStubs[3]],
  },
  {
    id: 5,
    code: 'P005',
    name: `${corporateStubs[0].category}${corporateStubs[0].name}`,
    dtype: 'corporate',
    personData: corporateStubs[0],
    address: addressStubs[11],
    phone: '053888888',
    fax: '053555888',
    contact: contactStubs[4],
    contacts: [
      contactStubs[4],
      contactStubs[10],
    ],
    bankAccounts: [
      bankAccountStubs[4],
      bankAccountStubs[10],
    ],
  },
  {
    id: 6,
    code: 'P006',
    name: `${corporateStubs[1].category}${corporateStubs[1].name}`,
    dtype: 'corporate',
    personData: corporateStubs[1],
    address: addressStubs[5],
    phone: '053777777',
    fax: '053555777',
    contact: contactStubs[5],
    contacts: [
      contactStubs[5],
    ],
    bankAccounts: [
      bankAccountStubs[5]
    ],
  },
  {
    id: 7,
    code: 'P007',
    name: `${citizenStubs[4].initname}${citizenStubs[4].firstname} ${citizenStubs[4].lastname}`,
    dtype: 'individual',
    personData: citizenStubs[4],
    address: addressStubs[6],
    contact: contactStubs[6],
    bankAccounts: [bankAccountStubs[6]],
  },
  {
    id: 8,
    code: 'P008',
    name: `${citizenStubs[5].initname}${citizenStubs[5].firstname} ${citizenStubs[5].lastname}`,
    dtype: 'individual',
    personData: citizenStubs[5],
    address: addressStubs[7],
    contact: contactStubs[7],
    bankAccounts: [bankAccountStubs[7]],
  },
  {
    id: 9,
    code: 'P009',
    name: `${corporateStubs[2].category}${corporateStubs[2].name}`,
    dtype: 'corporate',
    personData: corporateStubs[2],
    address: addressStubs[8],
    phone: '053444444',
    fax: '053555444',
    contact: contactStubs[8],
    contacts: [
      contactStubs[8],
      contactStubs[11],
    ],
    bankAccounts: [
      bankAccountStubs[8],
      bankAccountStubs[11],
    ],
  },
  {
    id: 10,
    code: 'P010',
    name: `${citizenStubs[6].initname}${citizenStubs[6].firstname} ${citizenStubs[6].lastname}`,
    dtype: 'individual',
    personData: citizenStubs[6],
    address: addressStubs[9],
    contact: contactStubs[9],
    bankAccounts: [bankAccountStubs[9]],
  },
];
