export let addressStubs = [
  {
    id: 1,
    address: `70 หมู่ที่ 10`,
    subdistrict: 'ร้องวัวแดง',
    district: 'สันกำแพง',
    province: 'เชียงใหม่',
    postalcode: '50130',
  },
  {
    id: 2,
    address: `66/66 ถ.ประชาอุทิศ`,
    subdistrict: 'บางซื่อ',
    district: 'จตุจักร',
    province: 'กรุงเทพมหานคร',
    postalcode: '10000',
  },
  {
    id: 3,
    address: `21 หมู่ที่ 6`,
    subdistrict: 'เจริญราษฎร',
    district: 'แม่ใจ',
    province: 'พะเยา่',
    postalcode: '56000',
  },
  {
    id: 4,
    address: `239 ถนนห้วยแก้ว
คณะวิศวกรรมศาสตร์ มหาวิทยาลัยเชียงใหม่`,
    subdistrict: 'สุเทพ',
    district: 'เมืองเชียงใหม่',
    province: 'เชียงใหม่',
    postalcode: '50200',
  },
  {
    id: 5,
    address: `115/2 หมูที่ 3`,
    subdistrict: 'ฟ้าฮ่าม',
    district: 'เมืองเชียงใหม่',
    province: 'เชียงใหม่',
    postalcode: '50000',
  },
  {
    id: 6,
    address: `111/3 หมู่ที่ 2`,
    subdistrict: 'หนองหอย',
    district: 'เมืองเชียงใหม',
    province: 'เชียงใหม่',
    postalcode: '50100',
  },
  {
    id: 7,
    address: `12/3 หมู่ที่ 4`,
    subdistrict: 'บ่อหิน',
    district: 'ดอยสะเก็ด',
    province: 'เชียงใหม่',
    postalcode: '50240',
  },
  {
    id: 8,
    address: `56/7 หมู่ที่ 8`,
    subdistrict: 'น้ำบ่อหลวง',
    district: 'หางดง',
    province: 'เชียงใหม่',
    postalcode: '50280',
  },
  {
    id: 9,
    address: `465 หมู่ที่ 8`,
    subdistrict: 'สันทรายน้อย',
    district: 'สันทราย',
    province: 'เชียงใหม่',
    postalcode: '50210',
  },
  {
    id: 10,
    address: `999 หมู่ที่ 9`,
    subdistrict: 'โป่งแยง',
    district: 'แม่ริม',
    province: 'เชียงใหม่',
    postalcode: '50240',
  },
  {
    id: 11,
    address: `123/45 หมู่ที่ 6 (พฤกษา)`,
    subdistrict: 'ต้นเปา',
    district: 'สันกำแพง',
    province: 'เชียงใหม่',
    postalcode: '50280',
  },
  {
    id: 12,
    address: `88/88 หมู่ที่ 8`,
    subdistrict: 'ริมใต้',
    district: 'แม่ริม',
    province: 'เชียงใหม่',
    postalcode: '50300',
  },
];

export let bankAccountStubs = [
  {
    id: 1,
    name: 'อนุชา ตันพูน',
    code: '7181069393',
    category: 'ออมทรัพย์',
    bank: 'ธนาคารกรุงศรีอยุธยา',
    branch: 'เซ็นทรัล เฟสติวัล เชียงใหม่',
  },
  {
    id: 2,
    name: 'วาริเดช สกุลถาวร',
    code: '7181066666',
    category: 'ออมทรัพย์',
    bank: 'ธนาคารกรุงศรีอยุธยา',
    branch: 'เซ็นทรัล เฟสติวัล เชียงใหม่',
  },
  {
    id: 3,
    name: 'พชร ตินะมาส',
    code: '7181063344',
    category: 'ออมทรัพย์',
    bank: 'ธนาคารออมสิน',
    branch: 'มหาวิทยาลัยเชียงใหม่',
  },
  {
    id: 4,
    name: 'เก่งกาจ อาจหาญ',
    code: '7181000123',
    category: 'ออมทรัพย์',
    bank: 'ธนาคารออมสิน',
    branch: 'มหาวิทยาลัยเชียงใหม่',
  },
  {
    id: 5,
    name: 'เชียงใหม่มายโฮม',
    code: '7181888888',
    category: 'ออมทรัพย์',
    bank: 'ธนาคารกสิกร',
    branch: 'รวมโชค',
  },
  {
    id: 6,
    name: 'พีดีแอล ไลท์ติ้ง เซ็นเตอร์',
    code: '7181777777',
    category: 'ออมทรัพย์',
    bank: 'ธนาคารกรุงเทพ',
    branch: 'ท่าแพ',
  },
  {
    id: 7,
    name: 'ดี สู้งาน',
    code: '7181001234',
    category: 'ออมทรัพย์',
    bank: 'ธนาคารกรุงเทพ',
    branch: 'ดอยสะเก็ด',
  },
  {
    id: 8,
    name: 'ขยัน ตั้งใจ',
    code: '7181005678',
    category: 'ออมทรัพย์',
    bank: 'ธนาคารกรุงไทย',
    branch: 'หางดง',
  },
  {
    id: 9,
    name: 'ศิรินาถ สมาร์ทโฮม เฟอร์นิเจอร์',
    code: '7181444444',
    category: 'ออมทรัพย์',
    bank: 'ธนาคารไทยพาณิชย์',
    branch: 'ช้างม่อย',
  },
  {
    id: 10,
    name: 'ขวัญชัย ใจดี',
    code: '7181999999',
    category: 'ออมทรัพย์',
    bank: 'ธนาคารกรุงเทพ',
    branch: 'กาดสามแยก',
  },
  {
    id: 11,
    name: 'เชียงใหม่มายโฮม',
    code: '7181999888',
    category: 'กระแสรายวัน',
    bank: 'ธนาคารกสิกร',
    branch: 'แม่ริม',
  },
  {
    id: 12,
    name: 'ศิรินาถ สมาร์ทโฮม เฟอร์นิเจอร์',
    code: '7181999444',
    category: 'กระแสรายวัน',
    bank: 'ธนาคารไทยพาณิชย์',
    branch: 'ท่าแพ',
  },
];

export let citizenStubs = [
  {
    id: 1,
    code: '3501300143304',
    dtype: 'citizen',
    initname: 'นาย',
    firstname: 'อนุชา',
    lastname: 'ตันพูน',
    birthDate: '1982-02-16',
    religious: 'พุทธ',
    address: addressStubs[0],
    issueDate: '2015-02-16',
    expiredDate: '2020-02-16',
  },
  {
    id: 2,
    code: '3501300143666',
    dtype: 'citizen',
    initname: 'นาย',
    firstname: 'วาริเดช',
    lastname: 'สกุลถาวร',
    birthDate: '1983-01-01',
    religious: 'พุทธ',
    address: addressStubs[1],
    issueDate: '2016-01-01',
    expiredDate: '2021-01-01',
  },
  {
    id: 3,
    code: '3501300143333',
    dtype: 'citizen',
    initname: 'นาย',
    firstname: 'พชร',
    lastname: 'ตินะมาส',
    birthDate: '1979-04-20',
    religious: 'พุทธ',
    address: addressStubs[2],
    issueDate: '2016-04-20',
    expiredDate: '2021-04-20',
  },
  {
    id: 4,
    code: '3501300555555',
    dtype: 'citizen',
    initname: 'นาย',
    firstname: 'เก่งกาจ',
    lastname: 'อาจหาญ',
    birthDate: '1990-05-05',
    religious: 'พุทธ',
    address: addressStubs[3],
    issueDate: '2015-05-05',
    expiredDate: '2020-05-05',
  },
  {
    id: 5,
    code: '3501300001234',
    dtype: 'citizen',
    initname: 'นาย',
    firstname: 'ดี',
    lastname: 'สู้งาน',
    birthDate: '',
    religious: '',
    address: addressStubs[6],
    issueDate: '2016-06-12',
    expiredDate: '2021-06-12',
  },
  {
    id: 6,
    code: '3501300005678',
    dtype: 'citizen',
    initname: 'นาย',
    firstname: 'ขยัน',
    lastname: 'ตั้งใจ',
    birthDate: '1975-10-15',
    religious: 'พุทธ',
    address: addressStubs[7],
    issueDate: '2015-10-15',
    expiredDate: '2020-10-15'
  },
  {
    id: 7,
    code: '3501399999999',
    dtype: 'citizen',
    initname: 'นาย',
    firstname: 'ขวัญชัย',
    lastname: 'ใจดี',
    birthDate: '1969-12-09',
    religious: 'พุทธ',
    address: addressStubs[9],
    issueDate: '2015-12-09',
    expiredDate: '2020-02-09'
  },
];

export let corporateStubs = [
  {
    id: 1,
    code: '0505557010381',
    dtype: 'corporate',
    registrationDate: '2014-11-03',
    category: 'บจก.',
    name: 'เชียงใหม่มายโฮม',
    main: false,
    branch: 'แม่ริม',
    address: addressStubs[4],
  },
  {
    id: 2,
    code: '0505560000910',
    dtype: 'corporate',
    registrationDate: '2017-01-19',
    category: 'บจก.',
    name: 'พีดีแอล ไลท์ติ้ง เซ็นเตอร์',
    main: true,
    branch: null,
    address: addressStubs[5],
  },
  {
    id: 3,
    code: '0505558006094',
    dtype: 'corporate',
    registrationDate: '2014-06-19',
    category: 'บจก.',
    name: 'ศิรินาถ สมาร์ทโฮม เฟอร์นิเจอร์',
    main: false,
    branch: 'สันทราย',
    address: addressStubs[8],
  },
];

export let contactStubs = [
  {
    id: 1,
    alias: 'ช.เอ',
    position: 'ผู้จัดการฝ่ายสำนักงาน',
    phones: [
      { id: 1, default: true, phone: '0891049355' },
      { id: 2, default: false, phone: '0931386996' },
    ],
    email: 'anucha@31con.co.th',
    lineId: 'anucha.t',
  },
  {
    id: 2,
    alias: 'ช.วา',
    position: 'ผู้จัดการฝ่ายก่อสร้าง',
    phones: [
      { id: 3, default: true, phone: '0897949701' },
      { id: 4, default: false, phone: '0931386665' },
    ],
    email: 'waridate@31con.co.th',
    lineId: 'waridate.s',
  },
  {
    id: 3,
    alias: 'อ.เอิง',
    position: 'ที่ปรึกษาฝ่ายIT',
    phones: [
      { id: 5, default: true, phone: '0899974137' },
    ],
    email: 'pachara@31con.co.th',
    lineId: 'pachara.t',
  },
  {
    id: 4,
    alias: 'ช.เก่ง',
    position: 'โฟร์แมน',
    phones: [
      { id: 6, default: true, phone: '08911155555' },
    ],
    email: 'keng.y@31con.co.th',
    lineId: 'keng.y',
  },
  {
    id: 5,
    alias: 'คุณนา',
    position: 'จัดซื้อ',
    phones: [
      { id: 7, default: true, phone: '0815558888' },
      { id: 8, default: false, phone: '053888888-1' },
    ],
    email: 'naja.myhome@gmail.com',
    lineId: 'naja.myhome',
  },
  {
    id: 6,
    alias: 'คุณตั๊ก',
    position: 'ผู้จัดการ',
    phones: [
      { id: 9, default: true, phone: '0893337777' },
      { id: 10, default: false, phone: '053777777-1' },
    ],
    email: 'tooktucky@pdl.com',
    lineId: 'tucky',
  },
  {
    id: 7,
    alias: 'ช.ดี',
    position: 'ผู้รับเหมางานโครงสร้าง',
    phones: [
      { id: 11, default: true, phone: '0890001234' },
    ],
    email: '',
    lineId: '',
  },
  {
    id: 8,
    alias: 'ช.ขยัน',
    position: 'ผู้รับเหมางานระบบ',
    phones: [
      { id: 12, default: true, phone: '0890005678' },
    ],
    email: 'kayan.tungjai@gmail.com',
    lineId: 'kayan.5678',
  },
  {
    id: 9,
    alias: 'คุณเจี๊ยบ',
    position: 'ธุรการ',
    phones: [
      { id: 13, default: true, phone: '0891114444' },
      { id: 14, default: false, phone: '053444444-1' },
    ],
    email: 'jeab.sirinarth@hotmail.com',
    lineId: 'jeab.sirinarth',
  },
  {
    id: 10,
    alias: 'คุณขวัญ',
    position: 'เจ้าของ',
    phones: [
      { id: 15, default: true, phone: '0893339999' },
      { id: 16, default: false, phone: '053555999' },
    ],
    email: 'nice.innovation@yahoo.com',
    lineId: 'nice.innovation',
  },
  {
    id: 11,
    alias: 'คุณฝน',
    position: 'พนักงานขายโครงการ',
    phones: [
      { id: 17, default: true, phone: '0891118888' },
      { id: 18, default: false, phone: '053888888-2' },
    ],
    email: 'fon.naruk@gmail.com',
    lineId: 'fon.naruk',
  },
  {
    id: 12,
    alias: 'คุณตุ้ม',
    position: 'บัญชี',
    phones: [
      { id: 19, default: true, phone: '0893334444' },
      { id: 20, default: false, phone: '053444444-2' },
    ],
    email: 'tum.love@hotmail.com',
    lineId: 'tum.love',
  },
];
